name: conda-env
channels:           #Select Repositories
    - defaults
    - conda-forge
#    - conda
#    - nodefaults   #Remove default Repository
dependencies:       #Packages
    - python
    - numpy
    - matplotlib
    - scipy
